// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenStromSpeicher
type AnlagenStromSpeicher struct {
	XMLName              xml.Name              `xml:"AnlagenStromSpeicher"`
	AnlagenStromSpeicher []AnlageStromSpeicher `xml:"AnlageStromSpeicher"`
}

type AnlageStromSpeicher struct {
	XMLName                          xml.Name `xml:"AnlageStromSpeicher"`
	MaStRNummer                      string   `xml:"MaStRNummer"`
	DatumLetzteAktualisierung        string   `xml:"DatumLetzteAktualisierung"`
	Registrierungsdatum              string   `xml:"Registrierungsdatum"`
	NutzbareSpeicherkapazitaet       float32  `xml:"NutzbareSpeicherkapazitaet"`
	VerknuepfteEinheitenMaStRNummern string   `xml:"VerknuepfteEinheitenMaStRNummern"`
	AnlageBetriebsstatus             uint     `xml:"AnlageBetriebsstatus"` // referenziert Katalogwert

}
