// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenEegBiomasse
type AnlagenEegBiomasse struct {
	XMLName            xml.Name            `xml:"AnlagenEegBiomasse"`
	AnlagenEegBiomasse []AnlageEegBiomasse `xml:"AnlageEegBiomasse"`
}

type AnlageEegBiomasse struct {
	XMLName                                xml.Name `xml:"AnlageEegBiomasse"`
	Registrierungsdatum                    string   `xml:"Registrierungsdatum"`
	DatumLetzteAktualisierung              string   `xml:"DatumLetzteAktualisierung"`
	EegInbetriebnahmedatum                 string   `xml:"EegInbetriebnahmedatum"`
	EegMaStRNummer                         string   `xml:"EegMaStRNummer"`
	AnlagenschluesselEeg                   string   `xml:"AnlagenschluesselEeg"`
	AnlagenkennzifferAnlagenregister       string   `xml:"AnlagenkennzifferAnlagenregister"`
	AnlagenkennzifferAnlagenregister_nv    string   `xml:"AnlagenkennzifferAnlagenregister_nv"`
	InstallierteLeistung                   float32  `xml:"InstallierteLeistung"`
	AusschliesslicheVerwendungBiomasse     string   `xml:"AusschliesslicheVerwendungBiomasse"`
	AusschreibungZuschlag                  string   `xml:"AusschreibungZuschlag"`
	ZugeordneteGebotsmenge                 float32  `xml:"ZugeordneteGebotsmenge"`
	Zuschlagsnummer                        string   `xml:"Zuschlagsnummer"`
	BiogasInanspruchnahmeFlexiPraemie      string   `xml:"BiogasInanspruchnahmeFlexiPraemie"`
	BiogasDatumInanspruchnahmeFlexiPraemie string   `xml:"BiogasDatumInanspruchnahmeFlexiPraemie"`
	BiogasLeistungserhoehung               string   `xml:"BiogasLeistungserhoehung"`
	BiogasDatumLeistungserhoehung          string   `xml:"BiogasDatumLeistungserhoehung"`
	BiogasUmfangLeistungserhoehung         float32  `xml:"BiogasUmfangLeistungserhoehung"`
	BiogasGaserzeugungskapazitaet          float32  `xml:"BiogasGaserzeugungskapazitaet"`
	BiogasGaserzeugungskapazitaet_nv       string   `xml:"BiogasGaserzeugungskapazitaet_nv"`
	BiogasHoechstbemessungsleistung        float32  `xml:"BiogasHoechstbemessungsleistung"`
	BiomethanErstmaligerEinsatz            string   `xml:"BiomethanErstmaligerEinsatz"`
	BiomethanErstmaligerEinsatz_nv         string   `xml:"BiomethanErstmaligerEinsatz_nv"`
	AnlageBetriebsstatus                   uint     `xml:"AnlageBetriebsstatus"` // referenziert Katalogwert
	VerknuepfteEinheitenMaStRNummern       string   `xml:"VerknuepfteEinheitenMaStRNummern"`
}
