// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenGasSpeicher
type AnlagenGasSpeicher struct {
	XMLName            xml.Name            `xml:"AnlagenGasSpeicher"`
	AnlagenGasSpeicher []AnlageGasSpeicher `xml:"AnlageGasSpeicher"`
}

type AnlageGasSpeicher struct {
	XMLName                          xml.Name `xml:"AnlageGasSpeicher"`
	MaStRNummer                      string   `xml:"MaStRNummer"`
	DatumLetzteAktualisierung        string   `xml:"DatumLetzteAktualisierung"`
	Speichername                     string   `xml:"Speichername"`
	Registrierungsdatum              string   `xml:"Registrierungsdatum"`
	AnlageBetriebsstatus             uint     `xml:"AnlageBetriebsstatus"` // referenziert Katalogwert
	VerknuepfteEinheitenMaStRNummern string   `xml:"VerknuepfteEinheitenMaStRNummern"`
}
