// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenEegSpeicher
type AnlagenEegSpeicher struct {
	XMLName            xml.Name            `xml:"AnlagenEegSpeicher"`
	AnlagenEegSpeicher []AnlageEegSpeicher `xml:"AnlageEegSpeicher"`
}

type AnlageEegSpeicher struct {
	XMLName                          xml.Name `xml:"AnlageEegSpeicher"`
	Registrierungsdatum              string   `xml:"Registrierungsdatum"`
	DatumLetzteAktualisierung        string   `xml:"DatumLetzteAktualisierung"`
	EegInbetriebnahmedatum           string   `xml:"EegInbetriebnahmedatum"`
	EegMaStRNummer                   string   `xml:"EegMaStRNummer"`
	VerknuepfteEinheitenMaStRNummern string   `xml:"VerknuepfteEinheitenMaStRNummern"`
}
