// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenKwk
type AnlagenKwk struct {
	XMLName    xml.Name    `xml:"AnlagenKwk"`
	AnlagenKwk []AnlageKwk `xml:"AnlageKwk"`
}

type AnlageKwk struct {
	XMLName                          xml.Name `xml:"AnlageKwk"`
	KwkMastrNummer                   string   `xml:"KwkMastrNummer"`
	AusschreibungZuschlag            string   `xml:"AusschreibungZuschlag"`
	Zuschlagnummer                   string   `xml:"Zuschlagnummer"`
	DatumLetzteAktualisierung        string   `xml:"DatumLetzteAktualisierung"`
	Inbetriebnahmedatum              string   `xml:"Inbetriebnahmedatum"`
	Registrierungsdatum              string   `xml:"Registrierungsdatum"`
	ThermischeNutzleistung           float32  `xml:"ThermischeNutzleistung"`
	ElektrischeKwkLeistung           float32  `xml:"ElektrischeKwkLeistung"`
	AnlageBetriebsstatus             uint     `xml:"AnlageBetriebsstatus"` // referenziert Katalogwert
	VerknuepfteEinheitenMaStRNummern string   `xml:"VerknuepfteEinheitenMaStRNummern"`
}
