// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// AnlagenEegSolar Alle öffentlichen Daten für eine Anlage der Art „EEG-Solar“.
type AnlagenEegSolar struct {
	XMLName         xml.Name         `xml:"AnlagenEegSolar"`
	AnlagenEegSolar []AnlageEegSolar `xml:"AnlageEegSolar"`
}

type AnlageEegSolar struct {
	XMLName                              xml.Name `xml:"AnlageEegSolar"`
	Registrierungsdatum                  string   `xml:"Registrierungsdatum"`                  // Registrierungsdatum der EEG-Anlage
	DatumLetzteAktualisierung            string   `xml:"DatumLetzteAktualisierung"`            // Datum der letzten Aktualisierung an diesem Objekt
	EegInbetriebnahmedatum               string   `xml:"EegInbetriebnahmedatum"`               // Inbetriebnahmedatum der EEG-Anlage
	EegMaStRNummer                       string   `xml:"EegMaStRNummer"`                       // MaStR-Nummer der Anlage
	InanspruchnahmeZahlungNachEeg        string   `xml:"InanspruchnahmeZahlungNachEeg"`        // Werden oder wurden für die Solaranlage Zahlungen Netzbetreibers in Anspruch genommen?
	AnlagenschluesselEeg                 string   `xml:"AnlagenschluesselEeg"`                 // Vom Netzbetreiber vergebene Kennziffer zur Identifikation der EEG-Anlage
	AnlagenkennzifferAnlagenregister     string   `xml:"AnlagenkennzifferAnlagenregister"`     // Anlagenkennziffer aus der Registrierungsbestätigung des Anlagenregister
	AnlagenkennzifferAnlagenregister_nv  string   `xml:"AnlagenkennzifferAnlagenregister_nv"`  // Anlagenkennziffer aus der Registrierungsbestätigung des Anlagenregister. Nicht-vorhanden Flag
	InstallierteLeistung                 float32  `xml:"InstallierteLeistung"`                 // Installierte Nettonennleistung (in kWh peak) der EEG-Anlage
	RegistrierungsnummerPvMeldeportal    string   `xml:"RegistrierungsnummerPvMeldeportal"`    // Durch die Bundesagentur vergeben Nummer bei der Registrierung im PV- Meldeportal
	RegistrierungsnummerPvMeldeportal_nv string   `xml:"RegistrierungsnummerPvMeldeportal_nv"` // Durch die Bundesagentur vergeben Nummer bei der Registrierung im PV- Meldeportal. Nicht- vorhanden Flag
	MieterstromZugeordnet                string   `xml:"MieterstromZugeordnet"`                // Gibt an, ob die Solaranlage Veräußerungsform des Mieterstromzuschlags zugeordnet wurde
	MieterstromRegistrierungsdatum       string   `xml:"MieterstromRegistrierungsdatum"`       // Datum, an dem die Anlage erstmalig der Veräußerungsform des Mieterstromzuschlags zugeordnet worden ist.
	MieterstromMeldedatum                string   `xml:"MieterstromMeldedatum"`                // -- nicht dokumentiert --
	MieterstromErsteZuordnungZuschlag    string   `xml:"MieterstromErsteZuordnungZuschlag"`    // Datum, an dem die Anlage erstmalig der Veräußerungsform des Mieterstromzuschlags zugeordnet worden ist.
	AusschreibungZuschlag                string   `xml:"AusschreibungZuschlag"`                // Angabe ob für die EEG- Anlage Im Rahmen des Ausschreibungsverfahren der Bundesnetzagentur ein Zuschlag erlangt wurde
	ZugeordneteGebotsmenge               float32  `xml:"ZugeordneteGebotsmenge"`               // Bezuschlagte Gebotsmenge, die der EEG-Anlage zugeordnet wurde
	Zuschlagsnummer                      string   `xml:"Zuschlagsnummer"`                      // Von der Bundesnetzagentur im Rahmen des Ausschreibungsverfahrens vergebene Nummern (Mehrfachnennung möglich)
	AnlageBetriebsstatus                 uint     `xml:"AnlageBetriebsstatus"`                 // Betriebsstatus der Anlage, welche sich aus den zugeordneten Einheiten ergibt. Katalogkategorie: Anlagenbetriebsstatus; referenziert Katalogwert
	VerknuepfteEinheitenMaStRNummern     string   `xml:"VerknuepfteEinheitenMaStRNummern"`     // Liste von MaStR Nummern mit den verknüpften Stromerzeugern

}
