// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// Bilanzierungsgebiete
type Bilanzierungsgebiete struct {
	XMLName              xml.Name              `xml:"Bilanzierungsgebiete"`
	Bilanzierungsgebiete []Bilanzierungsgebiet `xml:"Bilanzierungsgebiet"`
}

type Bilanzierungsgebiet struct {
	XMLName                               xml.Name `xml:"Bilanzierungsgebiet"`
	Id                                    uint     `xml:"Id"`
	Yeic                                  string   `xml:"Yeic"`
	BilanzierungsgebietNetzanschlusspunkt string   `xml:"BilanzierungsgebietNetzanschlusspunkt"`
	RegelzoneNetzanschlusspunkt           uint     `xml:"RegelzoneNetzanschlusspunkt"`
}
