// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// EinheitenStromVerbraucher
type EinheitenStromVerbraucher struct {
	XMLName                   xml.Name                  `xml:"EinheitenStromVerbraucher"`
	EinheitenStromVerbraucher []EinheitStromVerbraucher `xml:"EinheitStromVerbraucher"`
}

type EinheitStromVerbraucher struct {
	XMLName                                    xml.Name `xml:"EinheitStromVerbraucher"`
	EinheitMastrNummer                         string   `xml:"EinheitMastrNummer"`
	DatumLetzteAktualisierung                  string   `xml:"DatumLetzteAktualisierung"`
	LokationMaStRNummer                        string   `xml:"LokationMaStRNummer"` // referenziert Lokation
	NetzbetreiberpruefungStatus                uint     `xml:"NetzbetreiberpruefungStatus"`
	NetzbetreiberpruefungDatum                 string   `xml:"NetzbetreiberpruefungDatum"`
	AnlagenbetreiberMastrNummer                string   `xml:"AnlagenbetreiberMastrNummer"` // referenziert Marktakteur
	Land                                       uint     `xml:"Land"`                        // referenziert Katalogwert
	Bundesland                                 uint     `xml:"Bundesland"`                  // referenziert Katalogwert
	Landkreis                                  string   `xml:"Landkreis"`
	Gemeinde                                   string   `xml:"Gemeinde"`
	Gemeindeschluessel                         string   `xml:"Gemeindeschluessel"`
	Postleitzahl                               string   `xml:"Postleitzahl"`
	Gemarkung                                  string   `xml:"Gemarkung"`
	FlurFlurstuecknummern                      string   `xml:"FlurFlurstuecknummern"`
	Strasse                                    string   `xml:"Strasse"`
	StrasseNichtGefunden                       string   `xml:"StrasseNichtGefunden"`
	Hausnummer                                 string   `xml:"Hausnummer"`
	Hausnummer_nv                              string   `xml:"Hausnummer_nv"`
	HausnummerNichtGefunden                    string   `xml:"HausnummerNichtGefunden"`
	Adresszusatz                               string   `xml:"Adresszusatz"`
	Ort                                        string   `xml:"Ort"`
	Laengengrad                                float32  `xml:"Laengengrad"`
	Breitengrad                                float32  `xml:"Breitengrad"`
	Registrierungsdatum                        string   `xml:"Registrierungsdatum"`
	GeplantesInbetriebnahmedatum               string   `xml:"GeplantesInbetriebnahmedatum"`
	Inbetriebnahmedatum                        string   `xml:"Inbetriebnahmedatum"`
	DatumEndgueltigeStilllegung                string   `xml:"DatumEndgueltigeStilllegung"`
	DatumBeginnVoruebergehendeStilllegung      string   `xml:"DatumBeginnVoruebergehendeStilllegung"`
	DatumWiederaufnahmeBetrieb                 string   `xml:"DatumWiederaufnahmeBetrieb"`
	EinheitSystemstatus                        uint     `xml:"EinheitSystemstatus"`   // referenziert Katalogwert
	EinheitBetriebsstatus                      uint     `xml:"EinheitBetriebsstatus"` // referenziert Katalogwert
	BestandsanlageMastrNummer                  string   `xml:"BestandsanlageMastrNummer"`
	NichtVorhandenInMigriertenEinheiten        string   `xml:"NichtVorhandenInMigriertenEinheiten"`
	AltAnlagenbentreiberMastrNummer            string   `xml:"AltAnlagenbentreiberMastrNummer"`
	DatumDesBetreiberwechsels                  string   `xml:"DatumDesBetreiberwechsels"`
	DatumRegistrierungDesBetreiberwechsels     string   `xml:"DatumRegistrierungDesBetreiberwechsels"`
	Einsatzverantwortlicher                    string   `xml:"Einsatzverantwortlicher"`
	TechnischesInbetriebnahmedatum             string   `xml:"TechnischesInbetriebnahmedatum"`
	NameStromverbrauchseinheit                 string   `xml:"NameStromverbrauchseinheit"`
	AnzahlStromverbrauchseinheitenGroesser50Mw uint     `xml:"AnzahlStromverbrauchseinheitenGroesser50Mw"`
	PraequalifiziertGemaessAblav               string   `xml:"PraequalifiziertGemaessAblav"`
	AnteilBeinflussbareLast                    float32  `xml:"AnteilBeinflussbareLast"`
	ArtAbschaltbareLast                        uint     `xml:"ArtAbschaltbareLast"` // referenziert Katalogwert

}
