// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// EinheitenWind
type EinheitenWind struct {
	XMLName       xml.Name      `xml:"EinheitenWind"`
	EinheitenWind []EinheitWind `xml:"EinheitWind"`
}

type EinheitWind struct {
	XMLName                                            xml.Name `xml:"EinheitWind"`
	EinheitMastrNummer                                 string   `xml:"EinheitMastrNummer"`
	DatumLetzteAktualisierung                          string   `xml:"DatumLetzteAktualisierung"`
	LokationMaStRNummer                                string   `xml:"LokationMaStRNummer"` // referenziert Lokation
	NetzbetreiberpruefungStatus                        uint     `xml:"NetzbetreiberpruefungStatus"`
	NetzbetreiberpruefungDatum                         string   `xml:"NetzbetreiberpruefungDatum"`
	AnlagenbetreiberMastrNummer                        string   `xml:"AnlagenbetreiberMastrNummer"` // referenziert Marktakteur
	Land                                               uint     `xml:"Land"`                        // referenziert Katalogwert
	Bundesland                                         uint     `xml:"Bundesland"`                  // referenziert Katalogwert
	Landkreis                                          string   `xml:"Landkreis"`
	Gemeinde                                           string   `xml:"Gemeinde"`
	Gemeindeschluessel                                 string   `xml:"Gemeindeschluessel"`
	Postleitzahl                                       string   `xml:"Postleitzahl"`
	Gemarkung                                          string   `xml:"Gemarkung"`
	FlurFlurstuecknummern                              string   `xml:"FlurFlurstuecknummern"`
	Strasse                                            string   `xml:"Strasse"`
	StrasseNichtGefunden                               string   `xml:"StrasseNichtGefunden"`
	Hausnummer                                         string   `xml:"Hausnummer"`
	Hausnummer_nv                                      string   `xml:"Hausnummer_nv"`
	HausnummerNichtGefunden                            string   `xml:"HausnummerNichtGefunden"`
	Adresszusatz                                       string   `xml:"Adresszusatz"`
	Ort                                                string   `xml:"Ort"`
	Laengengrad                                        float32  `xml:"Laengengrad"`
	Breitengrad                                        float32  `xml:"Breitengrad"`
	Registrierungsdatum                                string   `xml:"Registrierungsdatum"`
	GeplantesInbetriebnahmedatum                       string   `xml:"GeplantesInbetriebnahmedatum"`
	Inbetriebnahmedatum                                string   `xml:"Inbetriebnahmedatum"`
	DatumEndgueltigeStilllegung                        string   `xml:"DatumEndgueltigeStilllegung"`
	DatumBeginnVoruebergehendeStilllegung              string   `xml:"DatumBeginnVoruebergehendeStilllegung"`
	DatumWiederaufnahmeBetrieb                         string   `xml:"DatumWiederaufnahmeBetrieb"`
	EinheitSystemstatus                                uint     `xml:"EinheitSystemstatus"`   // referenziert Katalogwert
	EinheitBetriebsstatus                              uint     `xml:"EinheitBetriebsstatus"` // referenziert Katalogwert
	BestandsanlageMastrNummer                          string   `xml:"BestandsanlageMastrNummer"`
	NichtVorhandenInMigriertenEinheiten                string   `xml:"NichtVorhandenInMigriertenEinheiten"`
	AltAnlagenbentreiberMastrNummer                    string   `xml:"AltAnlagenbentreiberMastrNummer"`
	DatumDesBetreiberwechsels                          string   `xml:"DatumDesBetreiberwechsels"`
	DatumRegistrierungDesBetreiberwechsels             string   `xml:"DatumRegistrierungDesBetreiberwechsels"`
	NameStromerzeugungseinheit                         string   `xml:"NameStromerzeugungseinheit"`
	Weic                                               string   `xml:"Weic"`
	Weic_nv                                            string   `xml:"Weic_nv"`
	WeicDisplayName                                    string   `xml:"WeicDisplayName"`
	Kraftwerksnummer                                   string   `xml:"Kraftwerksnummer"`
	Kraftwerksnummer_nv                                string   `xml:"Kraftwerksnummer_nv"`
	Energietraeger                                     uint     `xml:"Energietraeger"` // referenziert Katalogwert
	Bruttoleistung                                     float32  `xml:"Bruttoleistung"`
	Nettonennleistung                                  float32  `xml:"Nettonennleistung"`
	AnschlussAnHoechstOderHochSpannung                 string   `xml:"AnschlussAnHoechstOderHochSpannung"`
	Schwarzstartfaehigkeit                             string   `xml:"Schwarzstartfaehigkeit"`
	Inselbetriebsfaehigkeit                            string   `xml:"Inselbetriebsfaehigkeit"`
	Einsatzverantwortlicher                            string   `xml:"Einsatzverantwortlicher"`
	FernsteuerbarkeitNb                                string   `xml:"FernsteuerbarkeitNb"`
	FernsteuerbarkeitDv                                string   `xml:"FernsteuerbarkeitDv"`
	FernsteuerbarkeitDr                                string   `xml:"FernsteuerbarkeitDr"`
	Einspeisungsart                                    uint     `xml:"Einspeisungsart"` // referenziert Katalogwert
	PraequalifiziertFuerRegelenergie                   string   `xml:"PraequalifiziertFuerRegelenergie"`
	GenMastrNummer                                     string   `xml:"GenMastrNummer"` // referenziert EinheitGenehmigung
	NameWindpark                                       string   `xml:"NameWindpark"`
	Lage                                               uint     `xml:"Lage"`           // referenziert Katalogwert
	Seelage                                            uint     `xml:"Seelage"`        // referenziert Katalogwert
	ClusterOstsee                                      uint     `xml:"ClusterOstsee"`  // referenziert Katalogwert
	ClusterNordsee                                     uint     `xml:"ClusterNordsee"` // referenziert Katalogwert
	Hersteller                                         uint     `xml:"Hersteller"`     // referenziert Katalogwert
	Technologie                                        uint     `xml:"Technologie"`    // referenziert Katalogwert
	Typenbezeichnung                                   string   `xml:"Typenbezeichnung"`
	Nabenhoehe                                         float32  `xml:"Nabenhoehe"`
	Rotordurchmesser                                   float32  `xml:"Rotordurchmesser"`
	Rotorblattenteisungssystem                         string   `xml:"Rotorblattenteisungssystem"`
	AuflageAbschaltungLeistungsbegrenzung              string   `xml:"AuflageAbschaltungLeistungsbegrenzung"`
	AuflagenAbschaltungSchallimmissionsschutzNachts    string   `xml:"AuflagenAbschaltungSchallimmissionsschutzNachts"`
	AuflagenAbschaltungSchallimmissionsschutzTagsueber string   `xml:"AuflagenAbschaltungSchallimmissionsschutzTagsueber"`
	AuflagenAbschaltungSchattenwurf                    string   `xml:"AuflagenAbschaltungSchattenwurf"`
	AuflagenAbschaltungTierschutz                      string   `xml:"AuflagenAbschaltungTierschutz"`
	AuflagenAbschaltungEiswurf                         string   `xml:"AuflagenAbschaltungEiswurf"`
	AuflagenAbschaltungSonstige                        string   `xml:"AuflagenAbschaltungSonstige"`
	Wassertiefe                                        float32  `xml:"Wassertiefe"`
	Kuestenentfernung                                  float32  `xml:"Kuestenentfernung"`
	EegMaStRNummer                                     string   `xml:"EegMaStRNummer"` // referenziert AnlageEegWind

}
