// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// EinheitenGasSpeicher
type EinheitenGasSpeicher struct {
	XMLName              xml.Name             `xml:"EinheitenGasSpeicher"`
	EinheitenGasSpeicher []EinheitGasSpeicher `xml:"EinheitGasSpeicher"`
}

type EinheitGasSpeicher struct {
	XMLName                                xml.Name `xml:"EinheitGasSpeicher"`
	EinheitMastrNummer                     string   `xml:"EinheitMastrNummer"`
	DatumLetzteAktualisierung              string   `xml:"DatumLetzteAktualisierung"`
	LokationMaStRNummer                    string   `xml:"LokationMaStRNummer"` // referenziert Lokation
	NetzbetreiberpruefungStatus            uint     `xml:"NetzbetreiberpruefungStatus"`
	NetzbetreiberpruefungDatum             string   `xml:"NetzbetreiberpruefungDatum"`
	AnlagenbetreiberMastrNummer            string   `xml:"AnlagenbetreiberMastrNummer"` // referenziert Marktakteur
	Land                                   uint     `xml:"Land"`                        // referenziert Katalogwert
	Bundesland                             uint     `xml:"Bundesland"`                  // referenziert Katalogwert
	Landkreis                              string   `xml:"Landkreis"`
	Gemeinde                               string   `xml:"Gemeinde"`
	Gemeindeschluessel                     string   `xml:"Gemeindeschluessel"`
	Postleitzahl                           string   `xml:"Postleitzahl"`
	Gemarkung                              string   `xml:"Gemarkung"`
	FlurFlurstuecknummern                  string   `xml:"FlurFlurstuecknummern"`
	Strasse                                string   `xml:"Strasse"`
	StrasseNichtGefunden                   string   `xml:"StrasseNichtGefunden"`
	Hausnummer                             string   `xml:"Hausnummer"`
	Hausnummer_nv                          string   `xml:"Hausnummer_nv"`
	HausnummerNichtGefunden                string   `xml:"HausnummerNichtGefunden"`
	Adresszusatz                           string   `xml:"Adresszusatz"`
	Ort                                    string   `xml:"Ort"`
	Laengengrad                            float32  `xml:"Laengengrad"`
	Breitengrad                            float32  `xml:"Breitengrad"`
	Registrierungsdatum                    string   `xml:"Registrierungsdatum"`
	GeplantesInbetriebnahmedatum           string   `xml:"GeplantesInbetriebnahmedatum"`
	Inbetriebnahmedatum                    string   `xml:"Inbetriebnahmedatum"`
	DatumEndgueltigeStilllegung            string   `xml:"DatumEndgueltigeStilllegung"`
	DatumBeginnVoruebergehendeStilllegung  string   `xml:"DatumBeginnVoruebergehendeStilllegung"`
	DatumWiederaufnahmeBetrieb             string   `xml:"DatumWiederaufnahmeBetrieb"`
	EinheitSystemstatus                    uint     `xml:"EinheitSystemstatus"`   // referenziert Katalogwert
	EinheitBetriebsstatus                  uint     `xml:"EinheitBetriebsstatus"` // referenziert Katalogwert
	BestandsanlageMastrNummer              string   `xml:"BestandsanlageMastrNummer"`
	NichtVorhandenInMigriertenEinheiten    string   `xml:"NichtVorhandenInMigriertenEinheiten"`
	AltAnlagenbentreiberMastrNummer        string   `xml:"AltAnlagenbentreiberMastrNummer"`
	DatumDesBetreiberwechsels              string   `xml:"DatumDesBetreiberwechsels"`
	DatumRegistrierungDesBetreiberwechsels string   `xml:"DatumRegistrierungDesBetreiberwechsels"`
	NameGasspeicher                        string   `xml:"NameGasspeicher"`
	Speicherart                            uint     `xml:"Speicherart"` // referenziert Katalogwert
	MaximalNutzbaresArbeitsgasvolumen      float32  `xml:"MaximalNutzbaresArbeitsgasvolumen"`
	MaximaleEinspeicherleistung            float32  `xml:"MaximaleEinspeicherleistung"`
	MaximaleAusspeicherleistung            float32  `xml:"MaximaleAusspeicherleistung"`
	DurchschnittlicherBrennwert            float32  `xml:"DurchschnittlicherBrennwert"`
	Weic                                   string   `xml:"Weic"`
	Weic_Na                                string   `xml:"Weic_Na"`
	GenMastrNummer                         string   `xml:"GenMastrNummer"`      // referenziert EinheitGenehmigung
	SpeicherMaStRNummer                    string   `xml:"SpeicherMaStRNummer"` // referenziert AnlageGasSpeicher

}
