// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// Katalogwerte
type Katalogwerte struct {
	XMLName      xml.Name      `xml:"Katalogwerte"`
	Katalogwerte []Katalogwert `xml:"Katalogwert"`
}

type Katalogwert struct {
	XMLName            xml.Name `xml:"Katalogwert"`
	Id                 uint     `xml:"Id"`
	Wert               string   `xml:"Wert"`
	KatalogKategorieId uint     `xml:"KatalogKategorieId"` // referenziert Katalogkategorie

}
