// Code generated by go mastr/model generator; DO NOT EDIT.

package main

import (
	"encoding/xml"
)

// Lokationen
type Lokationen struct {
	XMLName    xml.Name   `xml:"Lokationen"`
	Lokationen []Lokation `xml:"Lokation"`
}

type Lokation struct {
	XMLName                          xml.Name `xml:"Lokation"`
	DatumLetzteAktualisierung        string   `xml:"DatumLetzteAktualisierung"`
	MastrNummer                      string   `xml:"MastrNummer"`
	NameDerTechnischenLokation       string   `xml:"NameDerTechnischenLokation"`
	Lokationtyp                      string   `xml:"Lokationtyp"`
	VerknuepfteEinheitenMaStRNummern string   `xml:"VerknuepfteEinheitenMaStRNummern"`
	NetzanschlusspunkteMaStRNummern  string   `xml:"NetzanschlusspunkteMaStRNummern"`
}
