CREATE TABLE "EinheitenSolar"(
  "EinheitMastrNummer" TEXT PRIMARY KEY,
  "DatumLetzteAktualisierung" TEXT,
  "LokationMaStRNummer" TEXT,
  "NetzbetreiberpruefungStatus" INTEGER,
  "NetzbetreiberpruefungDatum" TEXT,
  "AnlagenbetreiberMastrNummer" TEXT,
  "Land" INTEGER,
  "Bundesland" INTEGER,
  "Landkreis" TEXT,
  "Gemeinde" TEXT,
  "Gemeindeschluessel" TEXT,
  "Postleitzahl" TEXT,
  "Gemarkung" TEXT,
  "FlurFlurstuecknummern" TEXT,
  "Strasse" TEXT,
  "StrasseNichtGefunden" INTEGER, -- Boolean
  "Hausnummer" TEXT,
  "Hausnummer_nv" INTEGER,
  "HausnummerNichtGefunden" INTEGER,
  "Adresszusatz" TEXT,
  "Ort" TEXT,
  "Laengengrad" REAL,
  "Breitengrad" REAL,
  "Registrierungsdatum" TEXT,
  "GeplantesInbetriebnahmedatum" TEXT,
  "Inbetriebnahmedatum" TEXT,
  "DatumEndgueltigeStilllegung" TEXT,
  "DatumBeginnVoruebergehendeStilllegung" TEXT,
  "DatumWiederaufnahmeBetrieb" TEXT,
  "EinheitSystemstatus" INTEGER,
  "EinheitBetriebsstatus" INTEGER,
  "BestandsanlageMastrNummer" TEXT,
  "NichtVorhandenInMigriertenEinheiten" INTEGER,
  "AltAnlagenbentreiberMastrNummer" TEXT,
  "DatumDesBetreiberwechsels" TEXT,
  "DatumRegistrierungDesBetreiberwechsels" TEXT,
  "NameStromerzeugungseinheit" TEXT,
  "Weic" TEXT,
  "Weic_nv" INTEGER,
  "WeicDisplayName" TEXT,
  "Kraftwerksnummer" TEXT,
  "Kraftwerksnummer_nv" INTEGER,
  "Energietraeger" INTEGER,
  "Bruttoleistung" REAL,
  "Nettonennleistung" REAL,
  "AnschlussAnHoechstOderHochSpannung" INTEGER,
  "Schwarzstartfaehigkeit" INTEGER,
  "Inselbetriebsfaehigkeit" INTEGER,
  "Einsatzverantwortlicher" TEXT,
  "FernsteuerbarkeitNb" INTEGER,
  "FernsteuerbarkeitDv" INTEGER,
  "FernsteuerbarkeitDr" INTEGER,
  "Einspeisungsart" INTEGER,
  "PraequalifiziertFuerRegelenergie" INTEGER,
  "GenMastrNummer" TEXT,
  "ZugeordneteWirkleistungWechselrichter" TEXT,
  "GemeinsamerWechselrichterMitSpeicher" INTEGER,
  "AnzahlModule" INTEGER,
  "Lage" INTEGER,
  "Leistungsbegrenzung" INTEGER,
  "EinheitlicheAusrichtungUndNeigungswinkel" INTEGER,
  "Hauptausrichtung" INTEGER,
  "HauptausrichtungNeigungswinkel" INTEGER,
  "Nebenausrichtung" INTEGER,
  "NebenausrichtungNeigungswinkel" INTEGER,
  "InAnspruchGenommeneFlaeche" REAL,
  "ArtDerFlaecheIds" TEXT,
  "InAnspruchGenommeneAckerflaeche" REAL,
  "Nutzungsbereich" INTEGER,
  "EegMaStRNummer" TEXT
);

CREATE INDEX idx_EinheitenSolar_Ort ON EinheitenSolar(Ort);

.mode csv

-- Then run the following for every file:
--
-- .import EinheitenSolar_1_a.csv EinheitenSolar --skip 1
--
