create table 'EinheitenSolar' (
  'EinheitMastrNummer' text not null,
  'DatumLetzteAktualisierung' text not null,
  'LokationMaStRNummer' text,
  'NetzbetreiberpruefungStatus' integer not null,
  'NetzbetreiberpruefungDatum' text,
  'AnlagenbetreiberMastrNummer' text,
  'Land' integer not null,
  'Bundesland' integer,
  'Landkreis' text,
  'Gemeinde' text,
  'Gemeindeschluessel' text,
  'Postleitzahl' text not null,
  'Gemarkung' text,
  'FlurFlurstuecknummern' text,
  'Strasse' text,
  'StrasseNichtGefunden' text,
  'Hausnummer' text,
  'Hausnummer_nv' text,
  'HausnummerNichtGefunden' text,
  'Adresszusatz' text,
  'Ort' text,
  'Laengengrad' real,
  'Breitengrad' real,
  'Registrierungsdatum' text,
  'GeplantesInbetriebnahmedatum' text,
  'Inbetriebnahmedatum' text,
  'DatumEndgueltigeStilllegung' text,
  'DatumBeginnVoruebergehendeStilllegung' text,
  'DatumWiederaufnahmeBetrieb' text,
  'EinheitSystemstatus' integer,
  'EinheitBetriebsstatus' integer,
  'BestandsanlageMastrNummer' text,
  'NichtVorhandenInMigriertenEinheiten' text,
  'AltAnlagenbentreiberMastrNummer' text,
  'DatumDesBetreiberwechsels' text,
  'DatumRegistrierungDesBetreiberwechsels' text,
  'NameStromerzeugungseinheit' text not null,
  'Weic' text,
  'Weic_nv' text not null,
  'WeicDisplayName' text,
  'Kraftwerksnummer' text,
  'Kraftwerksnummer_nv' text not null,
  'Energietraeger' integer not null,
  'Bruttoleistung' real not null,
  'Nettonennleistung' real not null,
  'AnschlussAnHoechstOderHochSpannung' text,
  'Schwarzstartfaehigkeit' text,
  'Inselbetriebsfaehigkeit' text,
  'Einsatzverantwortlicher' text,
  'FernsteuerbarkeitNb' text,
  'FernsteuerbarkeitDv' text,
  'FernsteuerbarkeitDr' text,
  'Einspeisungsart' integer,
  'PraequalifiziertFuerRegelenergie' text,
  'GenMastrNummer' text,
  'ZugeordneteWirkleistungWechselrichter' text,
  'GemeinsamerWechselrichterMitSpeicher' integer,
  'AnzahlModule' integer,
  'Lage' integer,
  'Leistungsbegrenzung' integer,
  'EinheitlicheAusrichtungUndNeigungswinkel' text,
  'Hauptausrichtung' integer,
  'HauptausrichtungNeigungswinkel' integer,
  'Nebenausrichtung' integer,
  'NebenausrichtungNeigungswinkel' integer,
  'InAnspruchGenommeneFlaeche' real,
  'ArtDerFlaecheIds' text,
  'InAnspruchGenommeneAckerflaeche' real,
  'Nutzungsbereich' integer,
  'EegMaStRNummer' text,
  primary key ('EinheitMastrNummer')
);
